theme: jekyll-theme-cayman
title: Welcome to the Shivang’s homepage!
name: Shivang Bhatt
markdown: kramdown
description: Feel free to bookmark this to keep an eye on my project updates
permalink: /projects/:year/:month/:day/:title
